name: Check

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.5.x

      - name: Check formatting
        run: deno fmt --check

      - name: Type check library and examples
        run: deno check src/ examples/basic/src/main.tsx examples/directive/src/main.tsx

      - name: Run tests
        run: deno test
